Repository KNU-HAEDAL/Haedal-Rental-FE-v2, pull requests merged in 2025-04, with the labels that each got.

#57 [ESLint] import/resolver 설정 추가 #56
  eslint.config.js
Labels: 😡 Bug Fix

#60 [기능 구현] 관리자 페이지 물품 테이블 기능 구현
  src/features/admin/apis/item.api.ts
  src/features/admin/apis/item.type.ts
  src/features/admin/components/index.ts
  src/features/admin/components/table/AdminItemTable.tsx
  src/features/admin/components/table/index.ts
  src/features/admin/hooks/index.ts
  src/features/admin/hooks/useGetItemDetail.ts
  src/features/admin/mock/data/index.ts
  src/features/admin/mock/data/item-detail.ts
  src/features/admin/mock/data/items.ts
  src/features/admin/mock/handler/admin-Items.handler.ts
  src/features/admin/mock/handler/admin-item-list.handler.ts
  src/features/admin/mock/handler/index.ts
  src/features/admin/mock/handler/item-detail.handler.ts
  src/features/admin/mock/handler/item-list.handler.ts
  src/features/admin/model/types/item.type.ts
  src/features/admin/ui/section/AdminItemsTableSection.tsx
  src/features/apply-form/components/form/RentalPeriodField.tsx
  src/features/apply-form/mock/handler/item-rental.handler.ts
  src/pages/admin/RentedItemDetailPage.tsx
  src/shared/components/ui/badge.tsx
  src/shared/mocks/handlers.ts
  src/shared/types/item.type.ts
  src/shared/utils/date-format/format-date.ts
  src/shared/utils/format/category-format/category-format.ts
  src/shared/utils/format/category-format/index.ts
  src/shared/utils/format/date-format/date-after-days.ts
  src/shared/utils/format/date-format/format-date.ts
  src/shared/utils/format/date-format/index.ts
  src/shared/utils/format/index.ts
  src/shared/utils/format/status-format/index.ts
  src/shared/utils/format/status-format/status-format.ts
  src/shared/utils/index.ts
Labels: ✨ Feature, 📡 API

#66 [UI 구현] 회원가입 로그인 반응형 UI
  src/features/login/ui/form/LoginForm.tsx
  src/features/signup/ui/SignupForm.tsx
  src/pages/login/LoginPage.tsx
  src/pages/signup/SignupPage.tsx
  src/widgets/containers/AuthContainer.tsx
Labels: 🎨 Design

#67 [UI 구현] 메인 페이지 및 공통 컴포넌트 모바일 UI 구현, Global style 수정
  package.json
  pnpm-lock.yaml
  src/features/admin/components/box/ItemBox.tsx
  src/features/admin/components/table/AdminItemTable.tsx
  src/features/admin/ui/container/AdminTableContainer.tsx
  src/features/admin/ui/container/ItemImageContainer.tsx
  src/features/admin/ui/container/ItemNameContainer.tsx
  src/features/admin/ui/container/ItemPeriodContainer.tsx
  src/features/admin/ui/container/ItemTypeContainer.tsx
  src/features/admin/ui/form/AddItemForm.tsx
  src/features/admin/ui/section/AdminItemsTableSection.tsx
  src/features/admin/ui/section/ItemImageSection.tsx
  src/features/admin/ui/section/ItemNameSection.tsx
  src/features/admin/ui/section/ItemPeriodSection.tsx
  src/features/admin/ui/section/ItemTypeSection.tsx
  src/features/apply-form/components/form/CategorySelectField.tsx
  src/features/apply-form/components/form/ImageUploadField.tsx
  src/features/apply-form/components/form/ItemNameField.tsx
  src/features/apply-form/components/form/RentalPeriodField.tsx
  src/features/apply-form/ui/containers/ProgressContainer.tsx
  src/features/apply-form/ui/form/ApplyFormStep.tsx
  src/features/items/ui/ItemsTableSection.tsx
  src/features/main/ui/NavButtonSection.tsx
  src/features/main/ui/section/DescriptionSection.tsx
  src/features/main/ui/section/NavButtonSection.tsx
  src/features/my-rental/ui/MyRentalTableSection.tsx
  src/features/my-rental/ui/PenaltySection.tsx
  src/index.css
  src/pages/login/LoginPage.tsx
  src/pages/signup/SignupPage.tsx
  src/shared/components/features/buttons/BackButton.tsx
  src/shared/components/features/buttons/auth-button/index.ts
  src/shared/components/features/buttons/back-button/index.ts
  src/shared/components/features/buttons/index.ts
  src/shared/components/features/item-table/ItemTable.tsx
  src/shared/components/features/symbol-logo/SymbolLogo.tsx
  src/widgets/containers/AuthButtonContainer.tsx
  src/widgets/containers/AuthContainer.tsx
  src/widgets/containers/AuthLinkContainer.tsx
  src/widgets/containers/ButtonContainer.tsx
  src/widgets/containers/ContentsContainer.tsx
  src/widgets/containers/index.ts
  src/widgets/sections/DescriptionSection.tsx
  src/widgets/wrapper/PageWrapper.tsx
Labels: 🎨 Design
