Repository KNU-HAEDAL/Haedal-Rental-FE-v2, pull requests merged in 2025-03, with the labels that each got.

#9 [개발 환 경] shadcn/ui 컴포넌트 추가
  package.json
  pnpm-lock.yaml
  src/shared/components/ui/alert-dialog.tsx
  src/shared/components/ui/alert.tsx
  src/shared/components/ui/checkbox.tsx
  src/shared/components/ui/form.tsx
  src/shared/components/ui/input.tsx
  src/shared/components/ui/label.tsx
  src/shared/components/ui/progress.tsx
  src/shared/components/ui/skeleton.tsx
Labels: 📦 Environment, 🎨 Design

#13 [UI 구현] 로그인 페이지 (2)
  src/features/index.ts
  src/features/login/index.ts
  src/features/login/ui/index.ts
  src/features/login/ui/login-container.tsx
  src/pages/index.ts
  src/pages/login/LoginPage.tsx
  src/shared/components/features/index.ts
  src/shared/components/features/simple-logo/SimpleLogo.tsx
  src/shared/components/features/simple-logo/index.ts
  src/shared/components/index.ts
  src/shared/index.ts
Labels: 🎨 Design, ♻️ Refactoring

#14 [UI 구현] 회원가입 페이지
  src/features/index.ts
  src/features/login/ui/login-container.tsx
  src/features/signup/index.ts
  src/features/signup/model/index.ts
  src/features/signup/model/schema/index.ts
  src/features/signup/model/schema/signup-form.ts
  src/features/signup/model/types/index.ts
  src/features/signup/ui/index.ts
  src/features/signup/ui/signup-container.tsx
  src/pages/login/LoginPage.tsx
  src/pages/signup/SignupPage.tsx
  src/shared/components/ui/input.tsx
Labels: 🎨 Design

#16 [UI 구현] 물품 목록 페이지
  src/app/routes/router.tsx
  src/features/admin/model/data/item-type.ts
  src/features/admin/ui/table-container.tsx
  src/features/index.ts
  src/features/item-list/components/index.ts
  src/features/item-list/components/item-list-section.tsx
  src/features/item-list/index.ts
  src/features/item-list/model/data/available-item-list.ts
  src/features/item-list/model/data/index.ts
  src/features/item-list/model/index.ts
  src/features/item-list/ui/ItemListDescriptionSection.tsx
  src/features/item-list/ui/index.ts
  src/features/login/ui/login-container.tsx
  src/features/main/model/data/navigate-buttons-data.ts
  src/features/signup/ui/signup-container.tsx
  src/pages/admin/RentedItemDetailPage.tsx
  src/pages/admin/index.ts
  src/pages/item-list/ItemListPage.tsx
  src/shared/components/features/item-table/ItemTable.tsx
  src/shared/components/ui/button.tsx
  src/shared/constants/router-path.ts
  src/shared/utils/dynamic-path/DynamicPath.ts
Labels: 🎨 Design

#26 [파일/폴더구조] 관리자 페이지 파일 이름 및 구조 변경
  src/features/admin/components/box/ItemBox.tsx
  src/features/admin/components/box/index.ts
  src/features/admin/components/form/ItemField.tsx
  src/features/admin/components/form/index.ts
  src/features/admin/components/index.ts
  src/features/admin/ui/container/TableContainer.tsx
  src/features/admin/ui/container/index.ts
  src/features/admin/ui/form/AddItemForm.tsx
  src/features/admin/ui/form/index.ts
  src/features/admin/ui/index.ts
  src/features/admin/ui/section/ItemImageSection.tsx
  src/features/admin/ui/section/ItemNameSection.tsx
  src/features/admin/ui/section/ItemPeriodSection.tsx
  src/features/admin/ui/section/ItemTypeSection.tsx
  src/features/admin/ui/section/LenderInfoSection.tsx
  src/features/admin/ui/section/index.ts
  src/pages/admin/AdminPage.tsx
Labels: ♻️ Refactoring

#29 [포맷팅 수정] import order 설정 및 전체 포맷팅 수정사항 적용
  .prettierignore
  .prettierrc
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/app/providers/application-provider.tsx
  src/app/routes/router.tsx
  src/features/admin/ui/container/AdminTableContainer.tsx
  src/features/admin/ui/form/AddItemForm.tsx
  src/features/admin/ui/section/AdminItemsTableSection.tsx
  src/features/items/ui/ItemsTableSection.tsx
  src/features/my-rental/ui/MyRentalTableSection.tsx
  src/features/signup/ui/SignupForm.tsx
  src/pages/admin/AddItemPage.tsx
  src/pages/admin/AdminPage.tsx
  src/pages/admin/RentedItemDetailPage.tsx
  src/pages/items/ItemsPage.tsx
  src/pages/login/LoginPage.tsx
  src/pages/main/MainPage.tsx
  src/pages/my-rental/MyRentalPage.tsx
  src/pages/signup/SignupPage.tsx
  src/shared/components/features/auth-buttons/AuthButtons.tsx
  src/shared/components/features/custom-alter/admin-alter.tsx
  src/shared/components/features/symbol-logo/SymbolLogo.tsx
  src/shared/components/ui/alert-dialog.tsx
  src/shared/components/ui/alert.tsx
  src/shared/components/ui/badge.tsx
  src/shared/components/ui/button.tsx
  src/shared/components/ui/checkbox.tsx
  src/shared/components/ui/form.tsx
  src/shared/components/ui/label.tsx
  src/shared/components/ui/progress.tsx
  src/shared/constants/navigate-buttons-data.ts
  src/shared/hooks/useGetMockData.ts
  src/shared/libs/fetch-instance.ts
  src/shared/libs/utils.ts
  src/widgets/containers/AuthLinkContainer.tsx
  src/widgets/wrapper/PageWrapper.tsx
  tailwind.config.js
Labels: 📦 Environment, ♻️ Refactoring

#18 [UI구현] 대여 물품 신청 페이지
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/features/admin/model/data/index.ts
  src/features/admin/ui/container/ItemTypeContainer.tsx
  src/features/admin/ui/form/AddItemForm.tsx
  src/features/admin/ui/section/ItemTypeSection.tsx
  src/features/apply-form/components/NoticeMessage.tsx
  src/features/apply-form/components/box/CategorySelectBox.tsx
  src/features/apply-form/components/box/ImageUploadBox.tsx
  src/features/apply-form/components/box/ItemListBox.tsx
  src/features/apply-form/components/box/ItemNameBox.tsx
  src/features/apply-form/components/box/RentalPeriodBox.tsx
  src/features/apply-form/components/box/index.ts
  src/features/apply-form/components/index.ts
  src/features/apply-form/constants/category-data.ts
  src/features/apply-form/constants/index.ts
  src/features/apply-form/index.ts
  src/features/apply-form/model/hooks/index.ts
  src/features/apply-form/model/hooks/useRentalPeriod.tsx
  src/features/apply-form/model/index.ts
  src/features/apply-form/model/stores/index.ts
  src/features/apply-form/model/stores/useRentalForm.tsx
  src/features/apply-form/ui/index.ts
  src/features/apply-form/ui/section/BottomSection.tsx
  src/features/apply-form/ui/section/CreateSection.tsx
  src/features/apply-form/ui/section/NoticeSection.tsx
  src/features/apply-form/ui/section/SubmitSection.tsx
  src/features/apply-form/ui/section/index.ts
  src/features/items/ui/ItemsTableSection.tsx
  src/index.css
  src/pages/apply-form/ApplyFormPage.tsx
  src/shared/components/ui/calendar.tsx
  src/shared/components/ui/index.ts
  src/shared/components/ui/popover.tsx
  src/shared/components/ui/progress.tsx
  src/shared/constants/index.ts
  src/shared/constants/item-type.ts
  src/shared/constants/navigate-buttons-data.ts
  src/widgets/containers/ContentsContainer.tsx
Labels: 🎨 Design

#31 [UI 및 Form 기능구현] 물품 신청 폼 수정 및 리팩토링
  package.json
  pnpm-lock.yaml
  src/features/apply-form/components/NoticeMessage.tsx
  src/features/apply-form/components/box/NoticeMessageBox.tsx
  src/features/apply-form/components/box/ProgressBox.tsx
  src/features/apply-form/components/box/RentalPeriodBox.tsx
  src/features/apply-form/components/box/index.ts
  src/features/apply-form/components/button/DatePopoverTriggerButton.tsx
  src/features/apply-form/components/button/index.ts
  src/features/apply-form/components/form/CategorySelectField.tsx
  src/features/apply-form/components/form/ImageUploadField.tsx
  src/features/apply-form/components/form/ItemNameField.tsx
  src/features/apply-form/components/form/RentalPeriodField.tsx
  src/features/apply-form/components/form/index.ts
  src/features/apply-form/components/index.ts
  src/features/apply-form/hooks/index.ts
  src/features/apply-form/hooks/useGoStep.ts
  src/features/apply-form/index.ts
  src/features/apply-form/model/hooks/index.ts
  src/features/apply-form/model/hooks/useRentalPeriod.tsx
  src/features/apply-form/model/index.ts
  src/features/apply-form/model/schema/apply-form-schema.ts
  src/features/apply-form/model/schema/index.ts
  src/features/apply-form/model/stores/index.ts
  src/features/apply-form/model/stores/useRentalForm.tsx
  src/features/apply-form/ui/form/ItemApplyForm.tsx
  src/features/apply-form/ui/form/index.ts
  src/features/apply-form/ui/index.ts
  src/features/apply-form/ui/section/BottomSection.tsx
  src/features/apply-form/ui/section/CreateSection.tsx
  src/features/apply-form/ui/section/NoticeSection.tsx
  src/features/apply-form/ui/section/SubmitSection.tsx
  src/features/apply-form/ui/section/index.ts
  src/pages/apply-form/ApplyFormPage.tsx
  src/shared/components/ui/calendar.tsx
  src/shared/components/ui/dialog.tsx
  src/shared/components/ui/index.ts
  src/shared/utils/date-format/format-date.ts
  src/shared/utils/date-format/index.ts
Labels: ♻️ Refactoring

#37 [UI 구현] custom alert 구현 - 물품 삭제 alert 구현 및 적용
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/features/admin/components/alter/RemoveAlert.tsx
  src/features/admin/components/alter/index.ts
  src/features/admin/ui/section/AdminItemsTableSection.tsx
  src/pages/admin/AdminPage.tsx
  src/shared/components/ui/dialog.tsx
  src/shared/components/ui/index.ts
Labels: ✨ Feature

#43 [1차 배포] 1차 배포 후 버그 수정사항 반영
  src/features/apply-form/hooks/useGoStep.ts
  src/features/apply-form/ui/form/ItemApplyForm.tsx
  src/features/apply-form/ui/section/NoticeSection.tsx
  src/shared/components/features/simple-logo/SimpleLogo.tsx
Labels: 🚀 Deploy

#41 [api 통신 코드 작성] 서버 주소 추가 및 전체 api 코드 작성
  src/entities/auth/api/index.ts
  src/entities/auth/api/logout.api.ts
  src/entities/auth/api/refresh-token.api.ts
  src/entities/auth/index.ts
  src/entities/index.ts
  src/entities/user/api/index.ts
  src/entities/user/api/user-id.api.ts
  src/entities/user/index.ts
  src/entities/user/types/index.ts
  src/entities/user/types/rental-item-list.type.ts
  src/features/admin/apis/index.ts
  src/features/admin/apis/item.api.ts
  src/features/admin/apis/rental-check.api.ts
  src/features/admin/model/types/index.ts
  src/features/apply-form/apis/index.ts
  src/features/apply-form/apis/item-rental.api.ts
  src/features/items/apis/index.ts
  src/features/items/apis/item-list.api.ts
  src/features/login/apis/index.ts
  src/features/login/apis/login.api.ts
  src/features/login/ui/form/LoginForm.tsx
  src/features/my-rental/apis/index.ts
  src/features/my-rental/apis/item-return.api.ts
  src/features/signup/apis/duplicate-check.api.ts
  src/features/signup/apis/index.ts
  src/features/signup/apis/signup.api.ts
  src/shared/constants/item-type.ts
  src/shared/index.ts
  src/shared/libs/fetch-instance.ts
  src/shared/libs/index.ts
  src/shared/types/index.ts
  src/shared/types/item.type.ts
Labels: 📡 API

#44 [개발 환경] msw 환경 구현 및 관리자페이지 물품 mock 데이터 불러오기 구현
  eslint.config.js
  package.json
  public/mockServiceWorker.js
  src/features/admin/apis/index.ts
  src/features/admin/apis/item.api.ts
  src/features/admin/hooks/index.ts
  src/features/admin/hooks/useGetItemList.ts
  src/features/admin/index.ts
  src/features/admin/mock/data/index.ts
  src/features/admin/mock/data/item-list.ts
  src/features/admin/mock/handler/index.ts
  src/features/admin/mock/handler/item-list.handler.ts
  src/features/admin/mock/index.ts
  src/features/admin/ui/section/AdminItemsTableSection.tsx
  src/main.tsx
  src/shared/libs/fetch-instance.ts
  src/shared/mocks/browser.ts
  src/shared/mocks/handlers.ts
  src/shared/mocks/index.ts
Labels: ✨ Feature, 📦 Environment

#48 [msw] 물품 신청 폼 msw 코드 구현
  src/features/apply-form/apis/item-rental.api.ts
  src/features/apply-form/apis/item-rental.type.ts
  src/features/apply-form/components/form/CategorySelectField.tsx
  src/features/apply-form/mock/data/index.ts
  src/features/apply-form/mock/data/item-rental-data.ts
  src/features/apply-form/mock/handler/index.ts
  src/features/apply-form/mock/handler/item-rental.handler.ts
  src/features/apply-form/mock/index.ts
  src/features/apply-form/ui/form/ItemApplyForm.tsx
  src/shared/constants/item-type.ts
  src/shared/libs/fetch-instance.ts
  src/shared/mocks/handlers.ts
Labels: ✨ Feature
